blank_issues_enabled: true
contact_links:
  - name: Question or Feature Request
    url: https://github.com/microsoft/teams-sdk/discussions
    about: Please use GitHub Discussions for questions and feature requests
