[project]
name = "microsoft-teams-ai"
dynamic = ["version"]
description = "package to handle interacting with ai or llms"
authors = [{ name = "Microsoft", email = "TeamsAISDKFeedback@microsoft.com" }]
readme = "README.md"
requires-python = ">=3.12,<3.15"
repository = "https://github.com/microsoft/teams.py"
keywords = ["microsoft", "teams", "ai", "bot", "agents"]
license = "MIT"
dependencies = [
    "microsoft-teams-common",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"
raw-options = { root = "../.." }

[tool.hatch.build.targets.wheel]
packages = ["src/microsoft_teams", "src/microsoft"]

[tool.hatch.build.targets.sdist]
include = ["src"]

[tool.uv.sources]
microsoft_teams_common = { workspace = true }
